#!/bin/sh
# shellcheck shell=dash disable=SC2169 source=/dev/null
#
# Stop all init scripts in /etc/init.d
# executing them in reversed numerical order.

# shellcheck disable=SC2045
for i in $(ls -r /etc/init.d/S??*) ;do

  # Ignore dangling symlinks (if any).
  [[ ! -f "${i}" ]] && continue

  # make sure psplash is running
  if ! pgrep -n /usr/bin/psplash >/dev/null 2>&1; then
    /usr/bin/psplash -n 2>/dev/null &
  fi

  # put the psplash progess bar to the
  # corresponding level
  name=${i##*/}
  num=${name:1:2}
  /usr/bin/psplash-write "MSG Stopping ${name:3}..."
  /usr/bin/psplash-write "PROGRESS $((100-${num#0}))"

  case "$i" in
    *.sh)
      # Source shell script for speed.
      (
        trap - INT QUIT TSTP
        set stop
        . "${i}"
      )
      ;;
    *)
      # No sh extension, so fork subprocess.
      ${i} stop
      ;;
  esac
done

# make sure psplash is running
if ! pgrep -n /usr/bin/psplash >/dev/null 2>&1; then
  /usr/bin/psplash -n 2>/dev/null &
fi

/usr/bin/psplash-write "MSG Rebooting..."
/usr/bin/psplash-write "PROGRESS 0"

# quit psplash
/usr/bin/psplash-write "QUIT"
