#!/bin/sh
# shellcheck shell=dash disable=SC1090,SC2169,SC3010,SC3057
#
# Start all init scripts in /etc/init.d
# executing them in numerical order.

# make sure we have a secure umask
umask 0002

for i in /etc/init.d/S??* ;do

  # Ignore dangling symlinks (if any).
  [[ ! -f "${i}" ]] && continue

  # put the psplash progess bar to the
  # corresponding level
  name=${i##*/}
  num=${name:1:2}
  /usr/bin/psplash-write "MSG ${name:3}..."
  /usr/bin/psplash-write "PROGRESS $((${num#0}+1))"

  case "${i}" in
    *.sh)
      # Source shell script for speed.
      (
        trap - INT QUIT TSTP
        set start
        . "${i}"
      )
      ;;
    *)
      # No sh extension, so fork subprocess.
      ${i} start
    ;;
  esac
done

/usr/bin/psplash-write "PROGRESS 100"
