#!/bin/sh
#
# start script to download and setup the global environment from
# a boot server by trying to download certain netfiles which store
# environment parameters and will be put into /etc/env.d
#

TMPDIR=/tmp/config
ENVDIR=/etc/env.d
BASENAME=thinroot.conf
NUM=1

init() {
  # source /proc/cmdline to that we can grab BOOT_IMAGE
  source /proc/cmdline

  # get the BASE_PATH to the boot server from BOOT_IMAGE
  if [[ -n ${BOOT_IMAGE} ]]; then
    BASE_PATH=$(dirname ${BOOT_IMAGE})
    echo "BASE_PATH=${BASE_PATH}" >>${TMPDIR}/${BASENAME}

    # source the file with exporting all variables in it
    set -o allexport
    source ${TMPDIR}/${BASENAME}
    set +o allexport

    # link the file to /etc/env.d
    ln -sf ${TMPDIR}/${BASENAME} ${ENVDIR}/$(printf "%04d" ${NUM})-${BASENAME}.env
    NUM=$((++NUM))
  fi
}

install_net_overlay() {
  # this function downloads a global net overlay
  # file (overlay.tar.bz2) and installs it on top
  # of the rootfs
  /usr/bin/wget -q ${BASE_PATH}/overlay.pkg -O ${TMPDIR}/overlay.pkg
  if [[ $? -eq 0 ]]; then
    /bin/tar -C / -xf ${TMPDIR}/overlay.pkg
  fi
}

load_thinroot_network() {
  # get thinroot.network file and source all env variables in it
  /usr/bin/wget -q ${BASE_PATH}/conf/${BASENAME}.network -O ${TMPDIR}/${BASENAME}.network
  if [[ $? -eq 0 ]]; then
    # source the file with exporting all variables in it
    set -o allexport
    source ${TMPDIR}/${BASENAME}.network
    set +o allexport

    # link the file to /etc/env.d
    ln -sf ${TMPDIR}/${BASENAME}.network ${ENVDIR}/$(printf "%04d" ${NUM})-${BASENAME}.network.env
    NUM=$((++NUM))
  fi
}

load_thinroot_hosts() {
  # define a default CONFFILES variable to match the first
  # 3 character of the hostname
  CONFFILES=".group-$(echo ${HOSTNAME} | cut -c1-3)"

  # get thinroot.hosts file first
  /usr/bin/wget -q ${BASE_PATH}/conf/thinroot.hosts -O ${TMPDIR}/thinroot.hosts
  if [[ $? -eq 0 ]]; then

    # put all additional groups matching the hostname
    # to the host variable
    FOUND_GRP=$(grep -e ^${HOSTNAME} ${TMPDIR}/thinroot.hosts | cut -d" " -f "2-")
    if [[ -n "${FOUND_GRP}" ]]; then
      for grp in ${FOUND_GRP}; do
        # a comment lets us break out here
        if [[ "${grp}" == "#" ]]; then
          break
        fi
        if [[ -n "${grp}" && "${grp}" != "-" ]]; then
          CONFFILES="${CONFFILES} .group-${grp}"
        fi
      done
    fi
    MAC_ADDR=$(cat /sys/class/net/$(ip route show default | awk '/default/ {print $5}')/address)
    FOUND_GRP=$(grep -i ${MAC_ADDR} ${TMPDIR}/thinroot.hosts | cut -d" " -f "2-")
    if [[ -n "${FOUND_GRP}" ]]; then
      for grp in ${FOUND_GRP}; do
        # a comment lets us break out here
        if [[ "${grp}" == "#" ]]; then
          break
        fi
        if [[ -n "${grp}" && "${grp}" != "-" ]]; then
          CONFFILES="${CONFFILES} .group-${grp}"
        fi
      done
    fi
  fi
}

load_thinroot_hostipmac() {
  HOSTNAME=$(hostname)
  IP=$(ip route get 1 | awk '{print $NF;exit}')
  MAC=$(cat /sys/class/net/$(ip route show default | awk '/default/ {print $5}')/address | tr -d :)
  CONFFILES="${CONFFILES} -${HOSTNAME} -${IP} -${MAC}"
}

load_thinroot_conffiles() {
  for file in ${CONFFILES}; do
    # get thinroot.group-XXXX file and source all env variables in it
    /usr/bin/wget -q ${BASE_PATH}/conf/${BASENAME}${file} -O ${TMPDIR}/${BASENAME}${file}
    if [[ $? -eq 0 ]]; then
      # source the file with exporting all variables in it
      set -o allexport
      source ${TMPDIR}/${BASENAME}${file}
      set +o allexport

      # link the file to /etc/env.d
      ln -sf ${TMPDIR}/${BASENAME}${file} ${ENVDIR}/$(printf "%04d" ${NUM})-${BASENAME}${file}.env
      NUM=$((++NUM))
    fi
  done
}

start() {
  echo -n "Setup Environment: "

  # create tmpdir and envdir
  mkdir -p ${TMPDIR}
  mkdir -p ${ENVDIR}

  # initialize everything
  init

  if [[ -n ${BOOT_IMAGE} ]]; then
    # retrieve+install a net overlay file
    install_net_overlay

    # load thinroot.network env file
    load_thinroot_network

    # load/parse thinroot.hosts file
    load_thinroot_hosts

    # get hostname, ip and mac address
    load_thinroot_hostipmac

    # load all thinroot.conf.XXXXX conffiles
    load_thinroot_conffiles
  fi

  echo "OK"
}

restart() {
  start
}

case "$1" in
  start)
    start
  ;;
  restart|reload)
    restart
  ;;
  *)
    echo "Usage: $0 {start|restart}"
    exit 1
esac

exit $?
