#!/bin/sh
# shellcheck shell=dash disable=SC2169
#
# start/stop cron daemon
#

# function to update the crontab file and
# make sure that it is up to date
init() {

  # make sure /var/spool/cron/crontabs exists
  if [ ! -d /var/spool/cron/crontabs ]; then
    mkdir -p /var/spool/cron/crontabs
    chmod 775 /var/spool/cron/crontabs
  fi

  # make sure our system-wide crontab is taken for
  # being merged with the user configuration crontab
  if [[ -e /etc/crontab ]]; then
    cp -a /etc/crontab /var/spool/cron/crontabs/root
  fi
}

start() {
  echo -n "Starting crond: "
  init
  start-stop-daemon -S -q -b -m -p /var/run/crond.pid --exec /usr/sbin/crond -- -f -l 9
  echo "OK"
}

stop () {
  echo -n "Stopping crond: "
  start-stop-daemon -K -q -p /var/run/crond.pid
  echo "OK"
}

restart() {
  stop
  sleep 1
  start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart|reload)
    restart
  ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
