#!/bin/sh
# shellecheck shell=dash
#
# This script removes the model name symlink in /var/run/usbmount.
# Copyright (C) 2005 Martin Dickopp
#
# This file is free software; the copyright holder gives unlimited
# permission to copy and/or distribute it, with or without
# modifications, as long as this notice is preserved.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.
#
set -e

MOUNTNAME=$(grep "${UM_DEVICE}" /proc/mounts | grep /usbmount | awk '{print $2}')
if [ -n "${MOUNTNAME}" ]; then
  /bin/umount "${MOUNTNAME}"
  /bin/rmdir "${MOUNTNAME}"
fi

if [ -x /usr/bin/osd_cat ]; then
  export LANG=en_US.UTF-8
  export DISPLAY=:0
  COLOR=red
  echo "Unclean USB eject: Press ALT+F10 next time!" | /usr/bin/osd_cat -A center -p top -f '-*-fixed-bold-r-*-*-30-*-*-*-*-*-*-*' -c ${COLOR} -s 5 -d 10
fi

exit 0
